# Generated by Django 3.2.5 on 2021-07-26 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogHome', '0002_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='apone',
        ),
    ]
